### ISSUE TITLE
Allow multiple success or failure values in _poll (consistent with pending)

### ISSUE THREAD

**Issue by hongkongkiwi** [magodo/terraform-provider-restful#109] opened 2024-08-08 05:48 UTC
Is it possible to change the "success" & "failure" in the *_poll params to an array? e.g.
```
  poll_delete = {
    status_locator = "code"
    status = {
      success = ["204", "404"]
    }
  }
```
and it could work well for body also (this is a bad example but imagine another case where it could be a couple of different strings to indicate success):
```
  poll_update = {
    status_locator = "body.status"
    status = {
      success = ["Succeeded", "Updated"]
      failure = ["Failed"]
      pending = ["Pending"]
    }
  }
```

The only downside is that this is a breaking change as single values now need to be a single value array, but it keeps it consistent across success, pending, failure values and allows a bit more flexibility.

**Comment by hongkongkiwi** [comment] 2024-08-08 06:22
Oh I just realised also that "failure" is currently undocumented for resource :)

**Comment by magodo** [comment] 2024-08-08 13:44
As is said in https://github.com/magodo/terraform-provider-restful/issues/108#issuecomment-2275868342, I'm refrained to introduce the multiple success statuses. Also, `failure` is omit by design, which represents all statuses other than `success` + `pending`.

With this, I'm gonna close this issue.

**Closed by magodo** 2024-08-08 13:44 UTC

**Comment by hongkongkiwi** [comment] 2024-08-08 14:03
What I mean is that "failure" option of poll is not in the docs, but it is in your examples here:
- https://github.com/magodo/terraform-provider-restful/blob/53466abc4eff09356ff0cb50b05fd805ed9cf37c/examples/usecases/azure/virtual_network/main.tf#L65
- https://github.com/magodo/terraform-provider-restful/blob/53466abc4eff09356ff0cb50b05fd805ed9cf37c/examples/usecases/azure/route_table/main.tf#L65

It might be good add it to the documentation if it's a valid option that can be used or remove it if it shouldn't be used.
